# Generated by Django 5.2.4 on 2025-09-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='access_type',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share')], max_length=10),
        ),
    ]
