# Generated by Django 5.2.4 on 2025-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0002_alter_accesslog_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
