# Generated by Django 6.0.1 on 2026-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0002_sharedfilerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedfilerecord',
            options={'verbose_name': 'Shared File Record', 'verbose_name_plural': 'Shared File Records'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'Uploaded File', 'verbose_name_plural': 'Uploaded Files'},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
