# Generated by Django 6.0 on 2025-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0003_fileshare_encrypted_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='access_type',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share'), ('DELETE', 'Delete')], max_length=10),
        ),
    ]
