# Generated by Django 6.0.1 on 2026-03-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0003_alter_sharedfilerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together=set(),
        ),
    ]
