# Generated by Django 6.0.1 on 2026-03-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0004_alter_fileshare_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SharedFileRecord',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
