# Generated by Django 6.0.1 on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0005_remove_uploadedfile_user_delete_sharedfilerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='file_id_snapshot',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='file_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_sharing.sharedfile'),
        ),
    ]
